### ISSUE TITLE
IR Watchdog : Need Device To Test With

### ISSUE THREAD

**Issue by nelsonii** [ATMakersOrg/EyeAlert#11]
I'll need access to an eye gaze device (probably multiple brands) to see what they are doing with the IR.

? Is it always on, like a security cam ?
? Do they turn it on at scheduled intervals (we're talking milliseconds) ?

? How do they avoid "cross-talk" -- ex. what happens if someone pointed a TV remote control at the users eyes ?

**Comment by NachumLehman** [comment]
I can send you a tobii or two to play with. How long would you need it for?  If you want one long term, I do have a delivery of older models coming in next week and you can certainly hold onto one of those for a while.

**Comment by nelsonii** [comment]
I'm working on a more general solution to the IR Watchdog, so we (hopefully!) won't have to "program" it for each brand of eye gaze. 

Though, it's probably a good idea if I had a device for testing -- an old one is fine. I realize these are in demand and expensive.

**Comment by NachumLehman** [comment]
Can you send me your mailing address?  I have a Tobii i15 Classic which I can send you to test with the watchdog.

**Comment by nelsonii** [comment]
Sure thing. My address is:

Ron Nelson
913 Tammy Dr
Copperas Cove, TX 76522

**Comment by nelsonii** [comment]
Received Tobii Dynavox on Friday 2022-05-13. Thanks very much! Got it up and running. Now to practice eye gaze. :-)
